name: 🚀 Deploy to school on push
on: 
  push:
    branches:
      - main
jobs:
  deploy-main:
    name: 🎉 Deploy to school
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: milanmk/actions-file-deployer@master
      with:
        remote-host: ${{ secrets.school_server }}
        remote-port: ${{ secrets.school_port }}
        remote-protocol: ${{ secrets.school_protocol }}
        remote-user: ${{ secrets.school_username }}
        remote-password: ${{ secrets.school_password }}
        remote-path: ${{ secrets.school_dir }}
